### ISSUE TITLE
about ER-ACE-FA  Strategy

### ISSUE THREAD

**Issue by HandsLing** [HamedHemati/CIR#1]
thanks for your share, could you please tell me where is  ER-ACE-FA  Strategy code? thanks a lot

**Comment by HamedHemati** [comment]
Hi,

`ER-ACE-FA` is implemented in this file: `cir/strategies/er_ace_adaptive.py`. It uses `AdaptiveBuffer` which is the FA storage policy.

**Comment by HandsLing** [comment]
got it! thanks very much

**Comment by HandsLing** [comment]
I trained a task with 50 experiences, and when I trained about the 36th experience, the loss was nan. Do you know how to solve it

**Comment by HamedHemati** [comment]
Never had that issue for the FA buffer before. Are you using the same configurations provided by the scripts in `experiments/scripts/frequency_aware_buffer/fa-buffer_cifar100.sh`? Those are the configs that were used to obtain the results reported in the paper.
